name = "fpo-search-model-generator"
version = "0.0.2"
learning_rate = 0.001
max_epochs = 3
model_batch_size = 3000
embedding_batch_size = 3000
embedding_cache_checkpoint = 50000
vague_terms_data_file = "reference_data/vague_terms.csv"
extra_data_file = "reference_data/extra_references.csv"
cn_data_file = "reference_data/CN2024_SelfText_EN_DE_FR.csv"
tradesets_data_dir = "raw_source_data/tradesets_descriptions"
device = "xla" # see Trn1 guidance https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/programming-guide/training/pytorch-neuron-programming-guide.html
