name = "fpo-search-model-generator"
version = "1.0.1"
learning_rate = 0.0011
max_epochs = 4
model_batch_size = 1000
embedding_batch_size = 1000
embedding_cache_checkpoint = 50000
vague_terms_data_file = "reference_data/vague_terms.csv"
extra_data_file = "reference_data/extra_references.csv"
cn_data_file = "reference_data/CN2024_SelfText_EN_DE_FR.csv"
tradesets_data_dir = "raw_source_data/tradesets_descriptions"
device = "cuda"
embeddings-cache-enabled = false
transformer = "all-MiniLM-L6-v2"
known_english_words = "reference_data/known_english_words.txt"
known_non_english_words = "reference_data/known_non_english_words.txt"
preferred_languages = ["ENGLISH"]
detected_languages = ["ENGLISH", "FRENCH", "GERMAN", "SPANISH"]
minimum_relative_distance=0.7
