name = "fpo-search-model-generator"
version = "1.3.1"
learning_rate = 0.0011
max_epochs = 4
model_batch_size = 1000
embedding_batch_size = 200
vague_terms_data_file = "reference_data/vague_terms.csv"
extra_data_file = "reference_data/extra_references.csv"
cn_data_file = "reference_data/CN2024_SelfText_EN_DE_FR.csv"
exact_english_terms = "reference_data/exact_english_terms.txt"
partial_english_terms = "reference_data/partial_english_terms.txt"
partial_non_english_terms = "reference_data/partial_non_english_terms.txt"
tradesets_data_dir = "raw_source_data/tradesets_descriptions"
device = "cuda"
transformer = "all-mpnet-base-v2"
preferred_languages = [ "ENGLISH",]
detected_languages = [ "ENGLISH", "FRENCH", "GERMAN", "SPANISH",]
minimum_relative_distance = 0.7
model_dropout_layer_1_percentage = 0.2
model_dropout_layer_2_percentage = 0.5
