name = "fpo-search-model-generator"
version = "1.13.1"
learning_rate = 0.0011
max_epochs = 5
model_batch_size = 1024
embedding_batch_size = 250
vague_terms_data_file = "reference_data/vague_terms.csv"
extra_data_file = "reference_data/extra_references.csv"
cn_data_file = "reference_data/CN2025_SelfText_EN_DE_FR.csv"
exact_english_terms = "reference_data/exact_english_terms.txt"
partial_english_terms = "reference_data/partial_english_terms.txt"
partial_non_english_terms = "reference_data/partial_non_english_terms.txt"
brands_file = "reference_data/brands.csv"
tradesets_data_dir = "raw_source_data/tradesets_descriptions"
incorrect_description_pairs_file = "reference_data/incorrect_code_desc_pairs.csv"
phrases_to_remove_file = "reference_data/phrases_to_remove.txt"
device = "cuda"
transformer = "all-mpnet-base-v2"
preferred_languages = [ "ENGLISH",]
detected_languages = [ "ENGLISH", "FRENCH", "GERMAN", "SPANISH",]
minimum_relative_distance = 0.7
model_dropout_layer_1_percentage = 0.1
model_dropout_layer_2_percentage = 0.4
