service: fpo-search

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: python3.11
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}

functions:
  search:
    handler: handler.hello
     - httpApi:
         path: /hello
         method: get
