frameworkVersion: "3"
service: trade-tariff-lambdas-fpo-search

plugins:
  - serverless-domain-manager

provider:
  name: aws
  region: eu-west-2
  runtime: provided
  stage: ${env:STAGE}
  timeout: 29
  memorySize: 3072

  deploymentBucket:
    name: "trade-tariff-lambda-deployment-${aws:accountId}"

  ecr:
    images:
      fpo-search:
        uri: "${ssm:/${sls:stage}/FPO_SEARCH_ECR_URL}:${env:DOCKER_TAG}"

  environment:
    FPO_CLIENT_KEYS: ${env:FPO_CLIENT_KEYS}

  stackTags:
    customer: "fpo"
  tags:
    customer: "fpo"

  apiGateway:
    usagePlan:
      - apiStages:
          - api: ${self:service}-${env:STAGE}
            stage: ${env:STAGE}

functions:
  fpo_search:
    provisionedConcurrency: 3
    image: fpo-search
    events:
      - http:
          path: /fpo-code-search
          method: get
          private: true
      - http:
          path: /fpo-code-search
          method: post
          private: true
      - http:
          path: /healthcheck
          method: get
          private: false

custom:
  customDomain:
    domainName: ${param:custom_domain}
    stage: ${env:STAGE}
    basePath: ""
    certificateName: ${param:certificate_domain}
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
