frameworkVersion: "3"
service: trade-tariff-lambdas-fpo-search

provider:
  name: aws
  region: eu-west-2
  runtime: provided
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  timeout: 29
  memorySize: 3072

functions:
  fpo_search:
    image: ${env:DOCKER_IMAGE_URI}
    events:
      - http:
          path: /search
          method: get
      - http:
          path: /search
          method: post
