frameworkVersion: "3"
service: trade-tariff-lambdas-fpo-search

plugins:
  - serverless-domain-manager

provider:
  name: aws
  region: eu-west-2
  runtime: provided
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  timeout: 29
  memorySize: 3072
  environment:
    API_KEY: ${env:FPO_API_KEY}

functions:
  fpo_search:
    provisionedConcurrency: 3
    image: ${env:DOCKER_IMAGE_URI}
    events:
      - http:
          path: /fpo-code-search
          method: get
      - http:
          path: /fpo-code-search
          method: post

custom:
  customDomain:
    domainName: ${param:base_domain}
    stage: ${env:STAGE}
    basePath: search
    certificateName: ${param:base_domain}
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
