# Benchmark thresholds configuration for different sources
# High watermark - red build and slack notification
# Medium watermark - yellow build (just a slack notification)
# Low watermark - green build

[[thresholds]]
name = "RIS Classified thresholds top 1"
file = "benchmarking_data/results/benchmark_results_classified.json"
key = "result1Percent"
changeHigh = -3.0
changeMedium = -2.0
changeLow = -1.0
direction = "increase_is_good"

[[thresholds]]
name = "RIS Classified thresholds in top 5"
file = "benchmarking_data/results/benchmark_results_classified.json"
key = "inTop5Percent"
changeHigh = -3.0
changeMedium = -2.0
changeLow = -1.0
direction = "increase_is_good"

[[thresholds]]
name = "HMRC Good Goods Descriptions top 1"
file = "benchmarking_data/results/benchmark_results_good_goods.json"
key = "result1Percent"
changeHigh = -3.0
changeMedium = -2.0
changeLow = -1.0
direction = "increase_is_good"

[[thresholds]]
name = "HMRC Good Goods Descriptions in top 5"
file = "benchmarking_data/results/benchmark_results_good_goods.json"
key = "inTop5Percent"
changeHigh = -3.0
changeMedium = -2.0
changeLow = -1.0
direction = "increase_is_good"

[[thresholds]]
name = "Accuracy percentage"
file = "benchmarking_data/results/running_losses.json"
key = "accuracy"
interested_in = -1 # The last epoch only
changeHigh = -3.0
changeMedium = -2.0
changeLow = -1.0
direction = "increase_is_good"

[[thresholds]]
name = "Mean average Loss"
file = "benchmarking_data/results/running_losses.json"
key = "average_loss"
interested_in = -1 # The last epoch only
changeHigh = 0.30
changeMedium = 0.20
changeLow = 0.15
direction = "increase_is_bad"
