version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^dependabot/(?!docker/).*/
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/
orbs:
  serverless-framework: circleci/serverless-framework@2.0.1
  slack: circleci/slack@4.3.0
  tariff: trade-tariff/trade-tariff-ci-orb@0
  aws-cli: circleci/aws-cli@4.1.1

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small
  python:
    docker:
      - image: cimg/python:3.11.2
    resource_class: small
  node:
    docker:
      - image: cimg/node:21.2.0
    resource_class: small

jobs:
  build:
    executor: base
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: false
      - aws-cli/install
      - run:
          name: "Build and Push to ECR"
          command: ./.circleci/ecr.sh "/<< parameters.environment >>/FPO_SEARCH_ECR_URL"

  check:
    executor: python
    steps:
      - checkout
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install ruff
          ruff check .

  test:
    executor: python
    steps:
      - checkout
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install --no-cache-dir --upgrade torch --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir --upgrade -r requirements_lambda.txt
          python -m unittest -v -b

  deploy:
    executor: node
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - serverless-framework/setup
      - run: |
          npm install --dev serverless-domain-manager
      - run: make deploy-<< parameters.stage  >>
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: deployments
          event: pass
          template: basic_success_1

  smoketest:
    executor: base
    parameters:
      endpoint:
        type: string
    steps:
      - checkout
      - run: .circleci/bin/smoketest << parameters.endpoint >>

workflows:
  version: 2

  deploy-to-development:
    jobs:
      - check:
          <<: *filter-not-main

      - test:
          requires:
            - check
          <<: *filter-not-main

      - build:
          context: trade-tariff-terraform-aws-development
          environment: development
          <<: *filter-not-main

      - deploy:
          name: deploy-development
          stage: development
          context: trade-tariff-lambda-deployments-development
          requires:
            - test
            - build
          <<: *filter-not-main

      - smoketest:
          name: smoketest-development
          context: trade-tariff-lambda-deployments-development
          endpoint: https://search.dev.trade-tariff.service.gov.uk
          requires:
            - deploy-development
          <<: *filter-not-main

  deploy-to-staging:
    jobs:
      - deploy:
          name: deploy-staging
          stage: staging
          context: trade-tariff-lambda-deployments-staging
          <<: *filter-main

      - smoketest:
          name: smoketest-staging
          context: trade-tariff-lambda-deployments-staging
          endpoint: https://search.sandbox.trade-tariff.service.gov.uk
          requires:
            - deploy-staging
          <<: *filter-main

  # deploy-to-production:
  #   jobs:
  #     - deploy:
  #         name: deploy-production
  #         stage: production
  #         context: trade-tariff-lambda-deployments-production
  #         <<: *filter-main
