#!/usr/bin/env bash

[[ "$TRACE" ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail

GIT_REPO="trade-tariff-lambdas-fpo-search"
PYTHON_VERSION="3.11"

sudo yum remove openssl-devel awscli -y
sudo yum install -y \
  git               \
  gcc10             \
  gcc10-c++         \
  make              \
  patch             \
  zlib-devel        \
  zip               \
  unzip             \
  bzip2             \
  bzip2-devel       \
  readline-devel    \
  sqlite            \
  sqlite-devel      \
  openssl11-devel   \
  tk-devel          \
  libffi-devel      \
  xz-devel

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

export PYENV_ROOT="$HOME/.pyenv"
curl https://pyenv.run | bash
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

pyenv install "$PYTHON_VERSION"
pyenv global "$PYTHON_VERSION"

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> "$HOME/.bashrc"
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> "$HOME/.bashrc"
echo 'eval "$(pyenv init --path)"' >> "$HOME/.bashrc"
echo 'eval "$(pyenv init -)"' >> "$HOME/.bash_profile"

sudo alternatives --install /usr/bin/gcc gcc /usr/bin/gcc10-gcc 50
sudo alternatives --install /usr/bin/g++ g++ /usr/bin/g++10 50
sudo alternatives --set gcc /usr/bin/gcc10-gcc
sudo alternatives --set g++ /usr/bin/g++10

if ! command -v gcc10-gcc &>/dev/null; then
  echo "Error: gcc10-gcc not found"
  exit 1
fi
if ! command -v g++10 &>/dev/null; then
  echo "Error: g++10 not found"
  exit 1
fi

export CC=/usr/bin/gcc10-gcc
export CXX=/usr/bin/g++10

gcc --version
g++ --version

git clone "https://github.com/trade-tariff/${GIT_REPO}.git" --depth=1
echo "$PYTHON_VERSION" > "$GIT_REPO/.python-version"

cd "$GIT_REPO"

git fetch origin "$GIT_BRANCH:$GIT_BRANCH" && git checkout "$GIT_BRANCH"
python -m venv venv
source venv/bin/activate
make install

git checkout main && git branch -D "$GIT_BRANCH"
