name: bi-weekly-automated-model-build

on:
    schedule:
    - cron: "0 0 1,15 * *"    # Bi weekly (almost)

    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  automated-build-model:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRACE: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run create pr script
        run: .github/bin/createpr
