name: bi-weekly-automated-model-build

on:
    schedule:
    - cron: "0 0 1,15 * *"    # Bi weekly (almost)

    workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  automated-build-model:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Run create pr script
        run: .github/bin/createpr
