name: deploy-to-staging

on:
  push:
    branches:
       - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FPO_SEARCH_ECR_URL: 382373577178.dkr.ecr.eu-west-2.amazonaws.com/tariff-fpo-search-production
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::451934005581:role/GithubActions-Serverless-Lambda-Role
          aws-region: eu-west-2

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install requests==2.32.0

      - run: .github/bin/fetchmodel staging

      - run: .github/bin/download_search_references

      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - uses: trade-tariff/trade-tariff-tools/.github/actions/build-and-push@main
        with:
          ecr-url: 382373577178.dkr.ecr.eu-west-2.amazonaws.com/tariff-fpo-search-production
          ref: ${{ steps.docker-tag.outputs.DOCKER_TAG }}
        env:
          AWS_REGION: eu-west-2
          IAM_ROLE_ARN: arn:aws:iam::451934005581:role/GithubActions-Serverless-Lambda-Role

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::451934005581:role/GithubActions-Serverless-Lambda-Role
          aws-region: eu-west-2

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm install -g serverless@3

      - run: npm install -g serverless-domain-manager

      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - run: make deploy-staging
        env:
          STAGE: staging
          DOCKER_TAG: ${{ steps.docker-tag.outputs.DOCKER_TAG }}
          FPO_SEARCH_ECR_URL: 382373577178.dkr.ecr.eu-west-2.amazonaws.com/tariff-fpo-search-production

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: trade-tariff/trade-tariff-tools/.github/actions/slack-notify@main
        with:
          result: ${{ needs.deploy.result }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  e2etest:
    uses: trade-tariff/trade-tariff-tools/.github/workflows/e2e-fpo-tests.yml@main
    needs: deploy
    with:
      test-environment: staging
    secrets:
      scp-username: ${{ secrets.SCP_USERNAME }}
      scp-password: ${{ secrets.SCP_PASSWORD }}

  smoketest:
    needs: deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - run: .github/bin/smoketest https://search.staging.trade-tariff.service.gov.uk ${{ secrets.SMOKETEST_API_KEY }}
