name: nightly-ami-rotation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  rotate-amis:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844815912454:role/GithubActions-Build-Ami-Role
          aws-region: eu-west-2

      - uses: actions/checkout@v4

      - run: .github/bin/amicleanup --delete
